name: backend-deploy

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Docker build tag and push to ECR
        run: |
          echo "Building Docker image..."
          docker build -t backend:${{ github.sha }} ./backend
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 783490811281.dkr.ecr.us-east-1.amazonaws.com
          echo "Tagging Docker image..."
          docker tag backend:${{ github.sha }} 783490811281.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }}
          docker tag backend:${{ github.sha }} 783490811281.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          echo "Pushing Docker image to ECR..."
          docker push 783490811281.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }}
          docker push 783490811281.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    
      - name: backend instance refresh
        run: |
           aws autoscaling start-instance-refresh --auto-scaling-group-name backend-asg